name: "CI Build"
env:
  REGISTRY: "registry.digitalocean.com/youverify-hq"
  IMAGE_NAME: "youverify-web"

on:
  pull_request:
    branches:
      - prod-deploy
    types: [closed]

jobs:
  build:
    name: CI Build
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]
    if: github.event.pull_request.merged == true
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: yarn install

      - name: Lint Dockerfile
        uses: brpaz/hadolint-action@master
        with:
          dockerfile: "Dockerfile"

      - name: build, test and generate coverage report
        run: |
          yarn build
        env:
          CI: true

      # build and uplaod docker image
      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
          version: 1.57.0

      - name: Build container image
        run: docker build --build-arg BASE_URL -t $(echo $REGISTRY)/$(echo $IMAGE_NAME):$(echo $GITHUB_SHA | head -c7) .
        env:
          BASE_URL: ${{ secrets.PROD_BASE_URL }}

      - name: Log in to DigitalOcean Container Registry with short-lived credentials
        run: doctl registry login --expiry-seconds 600

      - name: Push image to DigitalOcean Container Registry
        run: docker push $(echo $REGISTRY)/$(echo $IMAGE_NAME):$(echo $GITHUB_SHA | head -c7)

      # deploy to kubernetes

      - name: Check out code
        uses: actions/checkout@v2
        with:
          repository: YouverifyHQ/services-kubernetes-manifests
          ref: master
          token: ${{ secrets.GHB_USER_TOKEN }}

      - name: Setup Kustomize
        uses: imranismail/setup-kustomize@v1
        with:
          kustomize-version: "4.0.4"

      - name: Update Kubernetes resources
        run: |
          cd $(echo $IMAGE_NAME)/kustomize/overlays/production
          kustomize edit set image image-name=$(echo $REGISTRY)/$(echo $IMAGE_NAME):$(echo $GITHUB_SHA | head -c7)
          cat kustomization.yaml

      - name: Commit Configuration changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git commit -am "Bump docker tag"

      - name: Push configuration changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GHB_USER_TOKEN }}
          branch: master
          repository: YouverifyHQ/services-kubernetes-manifests

      - name: Send Slack Notification
        uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          channel: "C01BL91B7TQ" #Channel ID
          username: "YV Github Action"
          author_name: "CI Details"
          # if_mention: "failure,cancelled"
          fields: repo,message,commit,author,action,eventName,ref,workflow,job,took # selectable (default: repo,message)
        env:
          GITHUB_TOKEN: ${{ github.token }} # optional
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }} # required
          MATRIX_CONTEXT: ${{ toJson(matrix) }} # required
        if: always() # Pick up events even if the job fails or is canceled.
